// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ytD0jm1H-17udMyRnwot54yrDtrE0sU',
    appId: '1:172802998173:web:6504235268cd13f5103974',
    messagingSenderId: '172802998173',
    projectId: 'coachiny-3ea54',
    authDomain: 'coachiny-3ea54.firebaseapp.com',
    storageBucket: 'coachiny-3ea54.firebasestorage.app',
    measurementId: 'G-DBF9XYC999',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAiOlF9fcn38tZz900vmuMln-C2khWVTw',
    appId: '1:172802998173:android:67df808e06d0e5ad103974',
    messagingSenderId: '172802998173',
    projectId: 'coachiny-3ea54',
    storageBucket: 'coachiny-3ea54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNeY2sgnvpBwYFn5MJT__QOJWDcPJzJsI',
    appId: '1:172802998173:ios:745c69798bb0e279103974',
    messagingSenderId: '172802998173',
    projectId: 'coachiny-3ea54',
    storageBucket: 'coachiny-3ea54.firebasestorage.app',
    iosBundleId: 'com.example.coachinyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNeY2sgnvpBwYFn5MJT__QOJWDcPJzJsI',
    appId: '1:172802998173:ios:745c69798bb0e279103974',
    messagingSenderId: '172802998173',
    projectId: 'coachiny-3ea54',
    storageBucket: 'coachiny-3ea54.firebasestorage.app',
    iosBundleId: 'com.example.coachinyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ytD0jm1H-17udMyRnwot54yrDtrE0sU',
    appId: '1:172802998173:web:3d720498d0247abc103974',
    messagingSenderId: '172802998173',
    projectId: 'coachiny-3ea54',
    authDomain: 'coachiny-3ea54.firebaseapp.com',
    storageBucket: 'coachiny-3ea54.firebasestorage.app',
    measurementId: 'G-968QB87RCT',
  );
}
